### ISSUE TITLE
Parsing succeeds with a wrong result

### ISSUE THREAD

**Issue by ohanhi** [rtfeldman/elm-iso8601#3]
The gist of it is the issue is this:
```elm
dateString =
    "2018-07-29T15:00:00.000Z"

parsedAndEncoded =
    dateString
        |> toTime
        |> Result.map fromTime
        -- Ok "2018-07-05T15:00:00.00Z"
```

I have confirmed that the parsing phase is the source of the issue: the Posix value is incorrect when you turn it into a date with JavaScript's `new Date(value)`. Here's a full example on [Ellie](https://ellie-test-19-cutover.now.sh/TX4BK4G5q2a1).

Let me know if I can help with this.

**Comment by justinmimbs** [comment]
I think this issue has to do with the leap year calculation. It should be fixed by this PR: https://github.com/rtfeldman/elm-iso8601/pull/2 :)

**Comment by rtfeldman** [comment]
@ohanhi can you try version `1.0.1` with @justinmimbs's fix, and close this issue if that fixes it for you?

**Comment by justinmimbs** [comment]
I just noticed that `fromTime` only [pads millis to 2 digits](https://github.com/rtfeldman/elm-iso8601/blob/rc1-1.0.1/src/Iso8601.elm#L367) instead of 3! So round-tripping any time with millis < 100 won't work till that's changed.

**Comment by rtfeldman** [comment]
Good point! Want to make a PR for that?

**Comment by justinmimbs** [comment]
Sure thing! https://github.com/rtfeldman/elm-iso8601/pull/4

**Comment by ohanhi** [comment]
And I can confirm this now works on my example, so I will close this issue! ([Ellie](https://ellie-test-19-cutover.now.sh/VH4dXdgGWYa1))
